// Generated by https://quicktype.io

import { IStockArticuloSucursal } from '@core/interfaces';

export interface ILineasStockArticulosSearch {
  _id: string;
  descripcion: string;
  articulos: IStockArticuloSucursal[];
}
