// Generated by https://quicktype.io

export interface INewArticuloStock {
  stock: number;
  stockBloqueado: number;
  stockMinimo: number;
  estado: boolean;
  articulo: string;
  codigo: number;
  codigoBarra: string;
  descripcion: string;
  precioVenta: number;
}
