// Generated by https://quicktype.io

export interface INewCliente {
  persona: INewPersona;
}

export interface INewPersona {
  nroDoc: string;
  nombreApellido: string;
  sexo: string;
  tipoDoc: string;
  tipoPersona: string;
}
