// Generated by https://quicktype.io

export interface INewCliente {
  persona: INewPersona;
  direcciones?: INewDireccion[];
}

export interface INewPersona {
  nroDoc: string;
  nombreApellido: string;
  sexo: string;
  tipoDoc: string;
  tipoPersona: string;
  correo?: string;
  celular?: string;
  direccion?: string;
  ciudad?: string;
  obs?: string;
}

export interface INewDireccion {
  direccion: string;
  ciudad?: string;
  predeterminado?: boolean;
  contacto?: string;
  obs?: string;
}
