// Generated by https://quicktype.io

export interface IEnvioNuevo {
  sucursalOrigen: string;
  sucursalDestino: string;
  detalles: IEnvioDetalle[];
}

export interface IEnvioDetalle {
  articulo: IEnvioArticulo;
  enviado: number;
  stockDisponible: number;
}

export interface IEnvioArticulo {
  _id: string;
  descripcion: string;
  codigo: string;
}
