import { IMetodoPago } from '@core/interfaces';
import { TipoPedido } from '../../core/interfaces/TipoPedidos';
// Generated by https://quicktype.io

export interface INewPedido {
  cliente?: Cliente;
  sucursal?: EntityWithId;
  impuesto: number;
  importeTotal: number;
  montoRecibido: number;
  vuelto: number;
  detalles: Detalle[];
  tipoPedido: TipoPedido;
  exentoIVA: boolean;
  metodosPago: IMetodoPago[];
}

export interface Cliente {
  _id: string;
  persona: Persona;
}

export interface Persona {
  nroDoc: string;
  ruc?: string;
  nombreApellido?: string;
}

export interface Detalle {
  articulo: EntityWithId;
  codigo: string;
  cantidad: number;
  precioUnitario: number;
  tipoImpuesto: number;
  descripcion: string;
  stockDisponible: number;
}

export interface EntityWithId {
  _id: string;
}
