// Generated by https://quicktype.io

export interface INewUser {
  username: string;
  nombreApellido: string;
  password: string;
  perfiles: string[];
  sucursal: string;
  passwordConfirmation: string;
}
