export interface ICaja {
  _id: string;
  descripcion: string;
  nro: number;
  estado: boolean;
  sucursal: {
    _id: string;
    descripcion: string;
  };
}

// Generated by https://quicktype.io

export interface ICierreCaja {
  monedas: ICashCierreCaja[];
  billetes: ICashCierreCaja[];
  totalEfectivo: number;
  totalDeposito: number;
  responsable: string;
}

export interface ICashCierreCaja {
  descripcion: string;
  cantidad: number;
}
