// Generated by https://quicktype.io

export interface ICliente {
  _id: string;
  persona: Persona;
  estado: boolean;
  usuarioAlta: UsuarioAlta;
  fechaAlta: string;
}

export interface Persona {
  _id: string;
  nroDoc: string;
  nombreApellido: string;
  tipoDoc: string;
  sexo: string;
  tipoPersona: string;
  usuarioAlta: string;
  fechaAlta: string;
}

export interface UsuarioAlta {
  _id: string;
  username: string;
}
