// Generated by https://quicktype.io

export interface ICliente {
  _id: string;
  persona: Persona;
  estado: boolean;
  usuarioAlta: UsuarioAlta;
  fechaAlta: string;
  direcciones?: Direccion[];
}

export interface Persona {
  _id: string;
  nroDoc: string;
  nombreApellido: string;
  tipoDoc: string;
  sexo: string;
  tipoPersona: string;
  usuarioAlta: string;
  fechaAlta: string;
  correo?: string;
  celular?: string;
  ciudad?: string;
  obs?: string;
  ruc?: string;
}

export interface UsuarioAlta {
  _id: string;
  username: string;
}

export interface Direccion {
  direccion: string;
  ciudad: string;
  predeterminado?: boolean;
  contacto: string;
  obs: string;
}
