// Generated by https://quicktype.io

import { ICategoriaMovimiento } from './categoriaMovimiento';

export interface IMovimiento {
  _id: string;
  descripcion: string;
  monto: number;
  categoria: ICategoriaMovimiento;
  esGasto: boolean;
  esIngreso: boolean;
  usuarioAlta: {
    _id: string;
    username: string;
  };
  fechaAlta: string;
  fechaModif: string;
  usuarioModif: {
    _id: string;
    username: string;
  };
}
