// Generated by https://quicktype.io

import { IArticulo } from './articulos';

export interface IStockArticuloSucursal {
  stockBloqueado: number;
  stock: number;
  stockMinimo: number;
  estado: boolean;
  _id: string;
  articulo: IArticulo;
  usuarioAlta: string;
  fechaAlta: string;
}
