// Generated by https://quicktype.io

export interface ISucursal {
  rangoInicial: number;
  nroActual: number;
  estado: boolean;
  _id: string;
  descripcion: string;
  direccion: string;
  ciudad: string;
  timbrado: number;
  establecimiento: number;
  puntoExpedicion: number;
  rangoFinal: number;
  usuarioAlta: UsuarioAlta;
  fechaAlta: string;
}

interface UsuarioAlta {
  username: string;
  uid: string;
}
